name: dogs_sitting
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  image_picker: ^0.8.9
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  firebase_core: ^2.30.1
  path: ^1.9.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo-transparent-png.png
    - assets/1423213-3715587.jpg
