name: dogs_sitting
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  image_picker: ^0.8.9
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.3
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  firebase_database: ^10.5.5
  logger: ^2.2.0
  path: ^1.9.0
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/12.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/5.png
    - assets/6.png
    - assets/7.png
    - assets/8.png
    - assets/9.png
    - assets/10.png
    - assets/11.png
    - assets/13.png
    - assets/14.png
    - assets/15.png
    - assets/16.png
    - assets/17.png
    - assets/18.png
    - assets/19.png
    - assets/20.png
    - assets/21.png
    - assets/23.png
    - assets/24.png
    - assets/25.png
    - assets/123.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/12.png"
